import { ThemeProvider } from "@/components/theme-provider";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import StoreProvider from "@/app/StoreProvider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <StoreProvider>
            <Header />
            {children}
            <Footer />
          </StoreProvider>
      </body>
    </html>
  );
}